import Head from 'next/head'
import BlogCard from '../components/BlogCard'
// importing dependencies 
import { GraphQLClient, gql } from 'graphql-request'

// API 
const graphcms =  new GraphQLClient('https://api-sa-east-1.hygraph.com/v2/clf6r3qlm5z9n01t5061l3pnt/master')

// create the query
const QUERY = gql`
  {
    posts{
      id,
      title,
      datePublished,
      slug,
      content{
        html
      }
      author{
        name,
        avatar{
          url
        }
      }
      coverPhoto {
          url
      }
    }
  }
`;

// request the query and return statics posts
export async function getStaticProps(){
  const {posts} = await graphcms.request(QUERY);
  return {
    props: {
      posts,
    },
    // regenerate static pages in case it gets updated
    revalidate: 10,
  };
}

// takes posts
export default function Home({posts}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {/* access to individual posts */}
        {posts.map((post) => ( 
          <BlogCard 
            title={post.title} 
            author={post.author} 
            coverPhoto={post.coverPhoto} 
            key={post.id} 
            datePublished={post.datePublished} 
            slug={post.slug}
            /> 
        ))}
      </main>
    </>
  )
}
